### ISSUE TITLE
Keyword argument not understood: data_format

### ISSUE THREAD

**Issue by sh4dowb** [aangfanboy/mnist_draw_with_opencv#1]
```
sh4dow@laptop:~/mnist_draw_with_opencv$ python3 mnistkerascnn.py 
Traceback (most recent call last):
  File "mnistkerascnn.py", line 162, in <module>
    model = create_model(load_from_hdd = True).MODEL
  File "mnistkerascnn.py", line 35, in __init__
    model = load_model(create_model.NAME + ".model")
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/saving.py", line 241, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/saving.py", line 318, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 171, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/sequential.py", line 316, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 559, in from_config
    return cls(**config)
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 372, in __init__
    super(Flatten, self).__init__(**kwargs)
  File "/home/sh4dow/.local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 132, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'data_format')

```

**Comment by aangfanboy** [comment]
If yolu didn't download model file, it might be happen because of that. If you downloaded, try to update tensorflow and keras. I'm in the school now, but i will check it in 6 hours or something.
